### ISSUE TITLE
Private: true dans le channel.send

### ISSUE THREAD

**Issue by ApixPlay** [mineralts/core#1]
```typescript
const channel = interaction.commandOptions.getChannel('salon') as TextChannel

await channel.send({content: 'Réponse à la commande !', private: true})
```

Envoi du message dans le channel mais il n'est pas en privé, en revanche le private fonctionne bien sur le interaction.reply !

**Comment by LeadcodeDev** [comment]
Thanks for the report, this issue will be patched in the next version of the core !
