### ISSUE TITLE
Rapport de bug [Mineral]

### ISSUE THREAD

**Issue by ghost** [mineralts/core#8]
![Erreur bot join other server then bot is running](https://user-images.githubusercontent.com/93717962/157985808-494e9c5f-f260-4835-976b-afe137fef1ba.PNG)
*Erreur quand un bot rejoint un autre serveur discord quand celui-ci est démarrer*

- Start bot
- Join server 1
- Aucune erreur après l'exécution de commande du bot ou autres ...
- Join server 2
- **ERREUR**

![Erreur bot then start bot but bot is on more servers](https://user-images.githubusercontent.com/93717962/157986002-11e80dd8-b01f-4195-8e56-e5f8ff4e78ac.PNG)
*Erreur quand on démarre le bot quand t-il est sur plusieurs serveur*

![Erreur bot with command slash discord](https://user-images.githubusercontent.com/93717962/157986076-74eaa992-22e1-4abd-9608-045d2181c938.PNG)
*Erreur quand on execute des commands ou autres quand il y a un autre bot discord ou les slash command de base de discord*

**Comment by LeadcodeDev** [comment]
Problem fixed and available in the next version, thank you very much !
